name: eco_snap
description: "An application that will help in separating waste"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+3
  audioplayers: ^5.2.1
  carousel_slider: ^5.1.1
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.0.0
  fl_chart: ^1.1.1
  intl: ^0.20.2
  google_sign_in: ^6.3.0
  firebase_auth: ^5.5.3
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  rename_app: ^1.6.5
  image_picker: ^1.0.7
  http: ^1.2.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/img/trash/
